2025-04-16 14:57:38,188 - INFO - ====== WebDriver manager ======
2025-04-16 14:57:38,269 - INFO - Get LATEST chromedriver version for google-chrome
2025-04-16 14:57:38,482 - INFO - Get LATEST chromedriver version for google-chrome
2025-04-16 14:57:38,706 - INFO - Driver [/home/nandinidalsaniya/.wdm/drivers/chromedriver/linux64/135.0.7049.95/chromedriver-linux64/chromedriver] found in cache
2025-04-16 14:57:40,749 - INFO - patching driver executable /home/nandinidalsaniya/.local/share/undetected_chromedriver/undetected_chromedriver
2025-04-16 14:59:41,498 - ERROR - Error in main run function: HTTPConnectionPool(host='localhost', port=58789): Read timed out. (read timeout=120)
Stack Trace:
Traceback (most recent call last):
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nandinidalsaniya/mcmaster-scraper/src/scraper/scraper.py", line 631, in run
    self.load_site()
  File "/home/nandinidalsaniya/mcmaster-scraper/src/scraper/scraper.py", line 105, in load_site
    self.driver.get(self.base_url)
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 665, in get
    return super().get(url)
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in get
    self.execute(Command.GET, {"url": url})
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/nandinidalsaniya/mcmaster-scraper/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=58789): Read timed out. (read timeout=120)

2025-04-16 14:59:41,627 - INFO - Driver closed successfully
